// Generated by scripts/generate-studio-schema.mjs; do not edit.
// Source SHA-256: 0657447a9bafdf3443e52692d08120d2409971ffca47ee279ebb4b9e5baa5397
export const NODE_TYPES = [
    "trigger", "action", "decision", "human_review", "approval", "system",
    "data_input", "data_output", "policy", "notification", "timer", "exception", "terminal",
];
