// Generated by scripts/generate-studio-schema.mjs; do not edit.
// Source SHA-256: 9ff41094ee8ddbfb1a646de34e95d95e9094c18dc69cb06685997d2ea2b5fa04
import { VersionSnapshotSchema, ScenarioRunSchema, parseWorkflowDocument } from "./schema.js";
export const MAX_CLOUD_BYTES = 256 * 1024;
export function parseCloudWorkspace(input) {
    if (!input || typeof input !== "object")
        throw new Error("Invalid account workspace.");
    const candidate = input;
    if (candidate.schemaVersion !== 1 || !Array.isArray(candidate.projects) || candidate.projects.length > 50)
        throw new Error("Invalid account workspace.");
    if (new TextEncoder().encode(JSON.stringify(input)).length > MAX_CLOUD_BYTES)
        throw new Error("Account workspace exceeds 256 KiB. Export older projects and history before saving.");
    const ids = new Set();
    const projects = candidate.projects.map((project) => {
        const parsed = parseWorkflowDocument(project.document);
        if (!parsed.ok || ids.has(parsed.document.id))
            throw new Error("Account workspace contains an invalid or duplicate project.");
        ids.add(parsed.document.id);
        const versions = VersionSnapshotSchema.array().parse(project.versions);
        const traces = ScenarioRunSchema.array().parse(project.traces);
        return { document: parsed.document, versions, traces };
    });
    return { schemaVersion: 1, projects };
}
