import { accountAvailability, billingAvailability, capabilityEvidenceDate, previewAvailability } from "./product-capabilities";

export const brandFacts = {
  schemaVersion: 1,
  lastVerified: capabilityEvidenceDate,
  publicName: "SolveLang", legalName: null, alternateNames: ["Solve Lang"],
  canonicalDomain: "https://www.solve-lang.com", entityType: "SoftwareApplication",
  foundingDate: null, headquartersOrPrimaryLocation: null, serviceAreas: [],
  shortDefinition: "SolveLang is a readable, explainable workflow language designed for AI-assisted business processes.",
  fullDescription: `SolveLang is an early-stage workflow language and tooling project for describing business processes in readable, source-controlled form. The Rust CLI is the canonical runtime. Workflow Intelligence Studio provides local-first deterministic analysis, while the browser preview supports a smaller safe subset. ${previewAvailability} ${accountAvailability} ${billingAvailability}`,
  primaryAudiences: ["Technical founders and hands-on operators", "Automation consultants and small agencies", "Engineering teams evaluating AI-assisted workflows", "Developers and technical evaluators"],
  products: [
    { name: "SolveLang language and CLI", status: "working-today", description: "Rust lexer, parser, AST runtime, interpreter, CLI, diagnostics, examples, and hardened execution modes." },
    { name: "Workflow Intelligence Studio", status: "working-today", description: "A local-first browser workspace for deterministic workflow modeling, analysis, simulation, traces, and evidence export." },
    { name: "Browser preview", status: "preview", description: "A pinned WebAssembly build of the canonical safe core; it is not the full hosted Rust runtime." },
    { name: "Workflow audit and support triage", status: "preview", description: previewAvailability },
    { name: "SolveLang API access and accounts", status: "deployed-gated", description: accountAvailability },
    { name: "API subscriptions", status: "production-canary", description: billingAvailability },
    { name: "Provider-backed integrations", status: "experimental-test-mode", description: "Provider use requires independent qualification, scoped credentials, and explicit authorization." },
  ],
  services: ["Workflow discovery and explainability audits", "Workflow prototyping and implementation support", "Automation documentation and rescue work"],
  features: ["Readable source-controlled workflow scripts", "Rust CLI validation and local execution", "Source-located diagnostics", "Hardened execution policies", "Deterministic Workflow Intelligence Studio analysis", "Browser-safe preview subset", "Experimental AI-provider boundary"],
  useCases: ["Customer support triage", "Lead qualification and routing", "Client intake", "Approval workflow design", "Document classification planning", "Recurring operations reporting", "Human-reviewed AI summarization"],
  differentiators: ["Readable workflow intent rather than visual-canvas-first configuration", "Version-control and code-review compatibility", "Explicit separation of deterministic logic and AI-assisted judgment", "Auditable safety and capability boundaries", "Local-first deterministic analysis"],
  limitations: [
    "SolveLang is an early beta and is not a production managed workflow platform.",
    "The browser preview supports a smaller subset than the Rust CLI runtime.",
    "Workflow Intelligence Studio analysis is deterministic, not AI analysis.",
    "Provider-backed AI, HTTP, file, and environment side effects require separate capability and credential gates.",
    "There are no published production reliability, scale, adoption, or performance benchmarks.",
    "Connected inbox-to-action automation and general managed workflow execution are not complete.",
  ],
  pricingSummary: billingAvailability,
  contactInformation: { email: "hello@solve-lang.com" },
  officialSocialProfiles: ["https://github.com/saiidz/solvelang"], parentOrganization: null, subBrands: [],
  verifiedClaims: ["The canonical SolveLang runtime is implemented in Rust.", "The CLI supports run, validate, tokens, AST, and help commands.", "The repository includes hardened execution modes and source-located diagnostics.", "Workflow Intelligence Studio performs deterministic local-first analysis.", "The public browser preview is intentionally smaller than the Rust runtime.", accountAvailability, billingAvailability],
  claimEvidence: [
    { claim: "positioning", source: "README.md" }, { claim: "runtime and CLI", source: "solvec/src/main.rs" },
    { claim: "language behavior", source: "docs/language-reference.md" }, { claim: "runtime safety", source: "docs/runtime-safety.md" },
    { claim: "Studio boundary", source: "docs/strategy.md" }, { claim: "browser preview boundary", source: "site/app/(english)/run/page.tsx" },
    { claim: "dated public capability evidence", source: "docs/production-launch-runbook.md" },
  ],
  unverifiedClaims: ["Production managed workflow execution", "Production API availability", "Enterprise compliance certification", "Production uptime or SLA", "Customer adoption or revenue", "Performance superiority over other workflow platforms"],
  prohibitedClaims: ["Production-ready runtime", "Full Rust runtime in the browser preview", "AI analysis for deterministic Studio checks", "Guaranteed workflow correctness", "Guaranteed automation outcomes", "Production API capability inferred only from billing or subscription screens", "Enterprise-grade durability without measured evidence"],
  privacyAndSecurityBoundaries: ["Never expose API keys, payment secrets, customer account data, or private workflow data in public metadata, structured data, sitemaps, or llms.txt.", "Account, checkout, billing, success, and private API routes are not public search products merely because they have browser routes.", "Search crawler policy is separate from model-training crawler policy."],
  approvedCallsToAction: ["Read the documentation", "Run the local Rust CLI", "Try the browser preview", "Open Workflow Intelligence Studio", "View the GitHub repository", "Map a workflow in the browser"],
} as const;
export type BrandFacts = typeof brandFacts;
